import React from 'react';
import LegalLayout from '../../components/LegalLayout';

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="May 30, 2026">
      <p>
        Please read these Terms of Service completely before using Crayon.dev which is operated by Crayon Inc.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
      </p>

      <h2>2. Autonomous Actions</h2>
      <p>
        Crayon provides autonomous software engineering agents capable of writing, modifying, and executing code. While we implement extensive safety boundaries, <strong>you are solely responsible for reviewing and approving all code changes</strong> before deploying them to production environments.
      </p>

      <h2>3. Intellectual Property</h2>
      <p>
        The Service and its original content, features, and functionality are and will remain the exclusive property of Crayon Inc. Any code generated by Crayon specifically for your repositories remains your intellectual property.
      </p>

      <h2>4. Limitation of Liability</h2>
      <p>
        In no event shall Crayon Inc. be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
      </p>
    </LegalLayout>
  );
}
