import chalk from "chalk";
import { Theme } from "cli-highlight";

// Inspired by Claude Code / One Dark
export const syntaxThemeDark: Theme = {
  keyword: chalk.hex("#c678dd"),
  built_in: chalk.hex("#e5c07b"),
  type: chalk.hex("#e5c07b"),
  literal: chalk.hex("#56b6c2"),
  number: chalk.hex("#d19a66"),
  regexp: chalk.hex("#98c379"),
  string: chalk.hex("#98c379"),
  subst: chalk.reset,
  symbol: chalk.hex("#61afef"),
  class: chalk.hex("#e5c07b"),
  function: chalk.hex("#61afef"),
  title: chalk.hex("#61afef"),
  params: chalk.reset,
  comment: chalk.hex("#5c6370").italic,
  doctag: chalk.hex("#c678dd"),
  meta: chalk.hex("#5c6370"),
  "meta-keyword": chalk.hex("#c678dd"),
  "meta-string": chalk.hex("#98c379"),
  section: chalk.hex("#e06c75").bold,
  tag: chalk.hex("#e06c75"),
  name: chalk.hex("#e06c75"),
  "builtin-name": chalk.hex("#e5c07b"),
  attr: chalk.hex("#d19a66"),
  attribute: chalk.hex("#d19a66"),
  variable: chalk.hex("#e06c75"),
  bullet: chalk.hex("#d19a66"),
  code: chalk.hex("#98c379"),
  emphasis: chalk.italic,
  strong: chalk.bold,
  formula: chalk.reset,
  link: chalk.underline.hex("#61afef"),
  quote: chalk.hex("#5c6370").italic,
  "selector-tag": chalk.hex("#e06c75"),
  "selector-id": chalk.hex("#d19a66"),
  "selector-class": chalk.hex("#d19a66"),
  "selector-attr": chalk.hex("#d19a66"),
  "selector-pseudo": chalk.hex("#c678dd"),
  "template-tag": chalk.hex("#c678dd"),
  "template-variable": chalk.hex("#e06c75"),
  addition: chalk.hex("#98c379"),
  deletion: chalk.hex("#e06c75"),
  default: chalk.hex("#abb2bf"),
};
